ALTER TABLE books ADD COLUMN IF NOT EXISTS new_id UUID DEFAULT gen_random_uuid() NOT NULL;
ALTER TABLE books DROP COLUMN IF EXISTS id;
ALTER TABLE books RENAME COLUMN new_id TO id;
ALTER TABLE books ALTER COLUMN id SET NOT NULL;