ALTER TABLE users ADD COLUMN IF NOT EXISTS new_id UUID DEFAULT gen_random_uuid() NOT NULL;
ALTER TABLE users DROP COLUMN IF EXISTS id;
ALTER TABLE users RENAME COLUMN new_id TO id;
ALTER TABLE users ADD CONSTRAINT pk_users_id PRIMARY KEY(id);