CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    firstName VARCHAR(30) NOT NULL,
    lastName VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL,
    hashedPassword VARCHAR(50) NOT NULL,
    dob TIMESTAMP NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
);